# examples/gallery.py
"""Real-robot gallery: load every URDF in examples/assets/gallery/, run batched
FK and an IK round-trip on each, and write an honest results table.

Every number in the table is measured by this script on your machine; robots
that fail to load are listed as failures, not hidden.

Usage:
  python examples/gallery.py --fetch     # download the robots (once)
  python examples/gallery.py             # run the gallery
"""
import argparse
import glob
import os
import time
import urllib.request

import torch

import kinfast

_BULLET = ("https://raw.githubusercontent.com/bulletphysics/bullet3/master/"
           "examples/pybullet/gym/pybullet_data")
ROBOTS = {  # third-party URDFs, fetched not vendored; see source repos for licenses
    "panda": f"{_BULLET}/franka_panda/panda.urdf",
    "kuka_iiwa": f"{_BULLET}/kuka_iiwa/model.urdf",
    "xarm6": f"{_BULLET}/xarm/xarm6_robot.urdf",
    "laikago": f"{_BULLET}/laikago/laikago.urdf",
    "a1": f"{_BULLET}/a1/a1.urdf",
    "minitaur": f"{_BULLET}/quadruped/minitaur.urdf",
    "racecar": f"{_BULLET}/racecar/racecar.urdf",
    "r2d2": f"{_BULLET}/r2d2.urdf",
    "cartpole": f"{_BULLET}/cartpole.urdf",
    "husky": f"{_BULLET}/husky/husky.urdf",
    "ur5": ("https://raw.githubusercontent.com/UM-ARM-Lab/pytorch_kinematics/"
            "master/tests/ur5.urdf"),
}


def fetch(dest):
    os.makedirs(dest, exist_ok=True)
    for name, url in ROBOTS.items():
        out = os.path.join(dest, f"{name}.urdf")
        try:
            urllib.request.urlretrieve(url, out)
            print(f"fetched {name}")
        except Exception as e:
            print(f"FAILED  {name}: {e}")


def evaluate(path):
    name = os.path.splitext(os.path.basename(path))[0]
    row = {"robot": name}
    try:
        robot = kinfast.load(path)
    except Exception as e:
        row["status"] = f"LOAD FAILED: {type(e).__name__}: {e}"
        return row
    row["links"] = robot.n_links
    row["dof"] = robot.dof
    row["status"] = "ok"

    if robot.dof == 0:
        row["fk_us"] = None
        row["ik_rate"] = None
        return row

    # batched FK timing (batch 1024, median of 5 runs after warmup)
    q = robot.random_configs(1024)
    robot.fk_all(q)
    times = []
    for _ in range(5):
        t0 = time.perf_counter()
        robot.fk_all(q)
        times.append(time.perf_counter() - t0)
    row["fk_us"] = sorted(times)[2] / 1024 * 1e6      # median, per-config microseconds

    # IK round-trip: targets generated by the robot's own FK are reachable
    n = 256
    target = robot.fk(robot.random_configs(n))
    q_sol, _ = robot.ik(target, iters=100, pos_only=True, restarts=8)
    err = (robot.fk(q_sol)[:, :3, 3] - target[:, :3, 3]).norm(dim=-1)
    row["ik_rate"] = (err < 5e-2).float().mean().item()
    return row


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="examples/assets/GALLERY.md")
    ap.add_argument("--dir", default="examples/assets/gallery")
    ap.add_argument("--fetch", action="store_true", help="download the robots first")
    args = ap.parse_args()

    if args.fetch:
        fetch(args.dir)

    paths = sorted(glob.glob(os.path.join(args.dir, "*.urdf")))
    if not paths:
        print("no robots found; run with --fetch first")
        return
    rows = [evaluate(p) for p in paths]

    lines = [
        "# kinfast real-robot gallery",
        "",
        "Every robot below is a real, unmodified URDF from a public repo",
        "(bullet3 pybullet_data; UR5 from pytorch_kinematics tests), loaded and",
        "exercised by `python examples/gallery.py` on this machine (CPU).",
        "",
        "| robot | links | dof | FK per config | IK round-trip (<5cm, restarts=8) |",
        "|---|---|---|---|---|",
    ]
    ok = fail = 0
    for r in rows:
        if r["status"] != "ok":
            lines.append(f"| {r['robot']} | | | {r['status']} | |")
            fail += 1
            continue
        ok += 1
        fk = f"{r['fk_us']:.1f} us" if r["fk_us"] is not None else "n/a (0 dof)"
        ik = f"{r['ik_rate']*100:.0f}%" if r["ik_rate"] is not None else "n/a"
        lines.append(f"| {r['robot']} | {r['links']} | {r['dof']} | {fk} | {ik} |")
    lines += ["", f"Loaded {ok}/{ok+fail} robots."]

    text = "\n".join(lines) + "\n"
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)
    print(text)


if __name__ == "__main__":
    main()
